YungChingProgram/Controllers/ColumnCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YungChingProgram.Models;
using YungChingProgram.Models.Database;
using YungChingProgram.Servicves;
using YungChingProgram.ViewModels;

namespace YungChingProgram.Controllers
{
    public class ColumnCRUDController : Controller
    {
        private readonly ColumnCRUDService _service = new ColumnCRUDService();
        public ActionResult Index()
        {
            try
            {
                ColumnCRUDViewModel columnCRUDViewModel = new ColumnCRUDViewModel();
                var selectList = _service.GetTypeSelectList();
                selectList.Insert(0, new SelectListItem { Value = "", Text = "請選擇" });
                columnCRUDViewModel.TypeSelectList = new SelectList(selectList, "Value", "Text");
                return View(columnCRUDViewModel);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public PartialViewResult ColumnCRUDPartialView(string name, string type)
        {
            try
            {
                ColumnCRUDPartialViewModel columnCRUDPartialViewModel = new ColumnCRUDPartialViewModel();
                columnCRUDPartialViewModel.ColumnCRUDDataModelList = _service.GetColumnCRUDDataList(name, type);
                var selectList = _service.GetTypeSelectList();
                selectList.Insert(0, new SelectListItem { Value = "", Text = "請選擇" });
                columnCRUDPartialViewModel.TypeSelectList = new SelectList(selectList, "Value", "Text");
                if (columnCRUDPartialViewModel.ColumnCRUDDataModelList == null)
                {
                    return PartialView(new ColumnCRUDPartialViewModel());
                }
                return PartialView(columnCRUDPartialViewModel);
            }
            catch (Exception ex)
            {
                return PartialView(new ColumnCRUDPartialViewModel());
            }
        }

        /// <summary>
        /// 新增或資料
        /// </summary>
        /// <returns></returns>
        public JsonResult InsertColumnCRUDData(ColumnCRUD columnCRUDData)
        {
            try
            {
                //判斷PKEY是否有填寫
                if (string.IsNullOrEmpty(columnCRUDData.Id))
                {
                    return Json(new { result = "人員代號為必填欄位" });
                }
                var result = _service.InsertColumnCRUDData(columnCRUDData);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }

        /// <summary>
        /// 新增或修改資料
        /// </summary>
        /// <returns></returns>
        public JsonResult UpdateColumnCRUDData(ColumnCRUDDataModel columnCRUDDataModel)
        {
            try
            {
                //判斷PKEY是否有填寫
                if (string.IsNullOrEmpty(columnCRUDDataModel.Id))
                {
                    return Json(new { result = "false" });
                }
                var result = _service.UpdateColumnCRUDData(columnCRUDDataModel);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }

        /// <summary>
        /// 刪除資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteColumnCRUDData(string pid)
        {
            try
            {
                //判斷PKEY是否有填寫
                if (string.IsNullOrEmpty(pid))
                {
                    return Json(new { result = "人員Id為空值，刪除失敗" });
                }
                var result = _service.DeleteColumnCRUDData(pid);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }
    }
}

YungChingProgram/Controllers/SingleCRUDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YungChingProgram.Models;
using YungChingProgram.Models.Database;
using YungChingProgram.Servicves;
using YungChingProgram.ViewModels;

namespace YungChingProgram.Controllers
{
    public class SingleCRUDController : Controller
    {
        private readonly SingleCRUDService _service = new SingleCRUDService();
        // GET: SingleCRUD
        public ActionResult Index()
        {
            try
            {
                SingleCRUDViewModel singleCRUDViewModel = new SingleCRUDViewModel();
                var selectList = _service.GetDtypeSelecList();
                selectList.Insert(0, new SelectListItem { Text = "請選擇", Value = "" });
                singleCRUDViewModel.DTypeSelectList = new SelectList(selectList, "Value", "Text");
                return View(singleCRUDViewModel);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public PartialViewResult SingleCRUDPartialView(string name, string type)
        {
            try
            {
                SingleCRUDPartialViewModel singleCRUDPartialViewModel = new SingleCRUDPartialViewModel();
                singleCRUDPartialViewModel.SingleCRUDModelList = _service.GetSingleCRUDDataList(name, type);
                if (singleCRUDPartialViewModel.SingleCRUDModelList == null)
                {
                    singleCRUDPartialViewModel.ErrorMessage = "查詢發生錯誤";
                    return PartialView(singleCRUDPartialViewModel);
                }
                var selectList = _service.GetDtypeSelecList();
                selectList.Insert(0, new SelectListItem { Value = "", Text = "請選擇" });
                singleCRUDPartialViewModel.DTypeSelectList = new SelectList(selectList, "Value", "Text");
                if (singleCRUDPartialViewModel.DTypeSelectList == null)
                {
                    return PartialView(new ColumnCRUDPartialViewModel());
                }
                return PartialView(singleCRUDPartialViewModel);
            }
            catch (Exception ex)
            {
                return PartialView();
            }
        }

        /// <summary>
        ///BKMBInfo維護畫面建置
        /// </summary>
        /// <param name="bkmbModel"></param>
        /// <param name="insertOrUpdate"></param>
        /// <returns></returns>
        public ActionResult SingleCRUDInfo(string id, string Mode)
        {
            try
            {
                SingleCRUDInfoViewModel singleCRUDInfoModel = new SingleCRUDInfoViewModel();
                var selectList = _service.GetDtypeSelecList();
                selectList.Insert(0, new SelectListItem { Text = "請選擇", Value = "" });
                singleCRUDInfoModel.DTypeSelectList = new SelectList(selectList, "Value", "Text");
                singleCRUDInfoModel.Mode = Mode;
                if (Mode == "Update")
                {
                    if (string.IsNullOrEmpty(id))
                    {
                        singleCRUDInfoModel.ErrorMessage = "需要修改資料的代碼為空值，修改動作失敗";
                        return View(singleCRUDInfoModel);
                    }
                    singleCRUDInfoModel.SingleCRUDModel = _service.GetSingleCRUDData(id);
                    if (singleCRUDInfoModel.SingleCRUDModel == null)
                    {
                        singleCRUDInfoModel.ErrorMessage = "查無該筆修改資料，修改動作失敗";
                        return View(singleCRUDInfoModel);
                    }
                    return View(singleCRUDInfoModel);
                }
                return View(singleCRUDInfoModel);
            }
            catch (Exception ex)
            {
                return View(new SingleCRUDInfoViewModel());
            }
        }

        /// <summary>
        /// 新增資料
        /// </summary>
        /// <returns></returns>
        public JsonResult InsertColumnCRUDData(SingleCRUD singleCRUDData)
        {
            try
            {
                //判斷PKEY是否有填寫
                if (string.IsNullOrEmpty(singleCRUDData.Id))
                {
                    return Json(new { result = "人員代號為必填欄位" });
                }
                var result = _service.InsertSingleCRUDData(singleCRUDData);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }

        /// <summary>
        /// 修改資料
        /// </summary>
        /// <returns></returns>
        public JsonResult UpdateSingleCRUDData(SingleCRUDModel singleCRUDDataModel)
        {
            try
            {
                //判斷PKEY是否有填寫
                if (string.IsNullOrEmpty(singleCRUDDataModel.Id))
                {
                    return Json(new { result = "false" });
                }
                var result = _service.UpdateSingleCRUDData(singleCRUDDataModel);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }

        /// <summary>
        /// 刪除資料
        /// </summary>
        /// <returns></returns>
        public ActionResult DeleteSingleCRUDDataList(List<string> didList)
        {
            try
            {
                //判斷PKEY是否有填寫
                foreach (var item in didList)
                {
                    if (string.IsNullOrEmpty(item))
                    {
                        return Json(new { result = "人員Id為空值" });
                    }
                }
                var result = _service.DeleteSingleCRUDDataList(didList);
                return Json(new { result = result });
            }
            catch (Exception ex)
            {
                return Json(new { result = "false" });
            }
        }
    }
}

YungChingProgram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="page-top">
    <!--Modal-->
    <div class="modal fade" id="TipModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">提示</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="TipSpan"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" id="tipsButton" class="btn btn-secondary" data-dismiss="modal">確認</button>
                </div>
            </div>
        </div>
    </div>

    <!--DeleteModal-->
    <div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">提示</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <span id="DeleteSpan"></span>
                </div>
                <div class="modal-footer">
                    <button id="DeleteConfirm" type="button" class="btn btn-secondary" data-dismiss="modal">確認</button>
                    <button id="DeleteCancel" type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("功能一", "Index", "ColumnCRUD")</li>
                    <li>@Html.ActionLink("功能二", "Index", "SingleCRUD")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="content">

            @RenderBody()
            </div>
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>